server:
  port: 8081

spring:
  application:
    name: account-service

  mongodb:
    uri: mongodb://localhost:27017/account_db

customer-service:
  base-url: http://localhost:8080

credit-service:
  base-url: http://localhost:8082

logging:
  level:
    root: INFO
    com.bootcamp.account_service: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: INFO
    org.springframework.web.reactive.function.client: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
